pipeline {
    agent {
        node {
            label 'agent01'
        }
    }
    environment {
        ENV = 'test'
        BUILD_TOOL = 'mvn'
        LIQUIBASE_HOME= 'D:/SETUPS/liquibase'
        
    }

    stages {
        stage ('Init') {
            steps {
                script {
                    sh(script: '',)
                }
            }
        }

        stage ('CI CD for database') {
            steps {
                script {
                    def LIQUIBASE = '${LIQUIBASE_HOME}/liquibase.bat --defaults-file=${WORKSPACE}/liquibase-mvn/liquibase.properties --search-path=${WORKSPACE}/liquibase-mvn/src/main/resources/'
                    sh(script: '${LIQUIBASE} status --verbose')
                    sh(script: '${LIQUIBASE} release-locks')
                    sh(script: '${LIQUIBASE} update')
                }
            }
        }
    }

    post {
        always {
            echo "Always echo this"
        }
        failure {
            echo "deploy fail"
        }
        success {
            echo "deploy success"
        }
    }
}
