pipeline {
    agent {
        node {
            label 'agent01'
        }
    }
    environment {
        ENV = 'test'
        BUILD_TOOL = 'mvn'
        LIQUIBASE_HOME= 'C:\Program Files\liquibase'
    }

    stages {
        stage ('Init') {
            steps {
                script {
                    sh(script: '',)
                }
            }
        }

        stage ('CI CD for database') {
            steps {
                script {
                    sh(script: '${LIQUIBASE_HOME}/liquibase --defaults-file=${WORKSPACE}/liquibase-mvn/liquibase.properties --search-path=${WORKSPACE}/liquibase-mvn/src/main/resources/ status --verbose',)
                }
            }
        }
    }

    post {
        always {
            echo "Always echo this"
        }
        failure {
            echo "deploy fail"
        }
        success {
            echo "deploy success"
        }
    }
}
